chunksize:
  type: integer
subchunk:
  type: integer
operation:
  type: string
  allowed:
    - liftover
    - reference
    - parse
    - preparse
    - GWAS_process
method:
  type: string
  allowed:
    - single
    - parallel
    - subparallel
mongo:
  type: boolean
runtime:
  type: string
  regex: \d{2}:\d{2}:\d{2}
vmem:
 type: string
 regex: \d{1,3}G