###############################################################################
# README                                                                      #
#                                                                             #
# All attributes under the indent of "meta_data" need to be filled in         #
# the "build" and "ethnicity" attributes are optional,                        #
# All attributes under the indent of "properties" do not need to be filled in #
# unless failure of column classification, then:                              #
# Fill in the indices corresponding to the "headers" under "header_idx"       #
# the "allowed" attribute show restrictions for input                         #
# Fill in all values in-line of : ,except for the list types eg. 'header_idx' #
# The comments describe the individual attributes below                       #
# A "-" signifies a new document, the attributes of this document all need to #
# be in the same indent of this hyphen (hyphen + space)                       #
###############################################################################

study_info:
    # may be modified, ensure unique values
    # for all the studyIDs in this file
    - studyID: GWAS01

      properties:
          # do not modify, only for reference
          headers:
            - SNP
            - CHR
            - BP
            - A1
            - A2
            - FRQ
            - Effect
            - SE
            - P
          # only modify if column classifier fails
          # fill in with hyphens like under "allowed"
          # allowed:
          # - 0
          # - 1
          # - 2
          # - 3
          # - 4
          # - 5
          # etc
          header_idx:
          # only modify if column classier fails
          separator:

      meta_data:
          # required field, type: string
          path:
          # required field, type: string
          effect_allele_column:
          # required field, type: integer
          n_studies:
          # required field, type: string
          phenotype:
          # choose one / leave blank
          # allowed:
          # - EUR
          # - AFR
          # - AMR
          # - EAS
          # - SAS
          ethnicity:
          # choose one / leave blank
          # allowed:
          # - hg16
          # - hg17
          # - hg18
          # - hg19
          # - hg38
          build:
    - studyID: GWAS02

      properties:
          # do not modify, only for reference
          headers:
            - SNP
            - CHR
            - BP
            - A1
            - A2
            - FRQ
            - Effect
            - SE
            - P
          # only modify if column classifier fails
          # fill in with hyphens like under "allowed"
          # allowed:
          # - 0
          # - 1
          # - 2
          # - 3
          # - 4
          # - 5
          # etc
          header_idx:
          # only modify if column classier fails
          separator:

      meta_data:
          # required field, type: string
          path:
          # required field, type: string
          effect_allele_column:
          # required field, type: integer
          n_studies:
          # required field, type: string
          phenotype:
          # choose one / leave blank
          # allowed:
          # - EUR
          # - AFR
          # - AMR
          # - EAS
          # - SAS
          ethnicity:
          # choose one / leave blank
          # allowed:
          # - hg16
          # - hg17
          # - hg18
          # - hg19
          # - hg38
          build: